// initialize tarot card states as a nested hashmap
// ignore_for_file: file_names

Map<int, Map> cardstates = {
  0: {
    "isFlipped": false,
    "flipCount": 0,
    "cardTitle": "Click me!",
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  1: {
    "isFlipped": false,
    "flipCount": 0,
    "cardTitle": "Click me!",
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  2: {
    "isFlipped": false,
    "flipCount": 0,
    "cardTitle": "Click me!",
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  3: {
    "isFlipped": false,
    "flipCount": 0,
    "cardTitle": "Click me!",
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  4: {
    "isFlipped": false,
    "flipCount": 0,
    "cardTitle": "Click me!",
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  5: {
    "isFlipped": false,
    "flipCount": 0,
    "cardTitle": "Click me!",
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  6: {
    "isFlipped": false,
    "flipCount": 0,
    "cardTitle": "Click me!",
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  7: {
    "isFlipped": false,
    "flipCount": 0,
    "cardTitle": "Click me!",
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  8: {
    "isFlipped": false,
    "flipCount": 0,
    "cardTitle": "Click me!",
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  9: {
    "isFlipped": false,
    "flipCount": 0,
    "cardTitle": "Click me!",
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  10: {
    "isFlipped": false,
    "flipCount": 0,
    "cardTitle": "Click me!",
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
};