// initialize tarot card states as a nested hashmap

Map<int, Map> cardstates = {
  0: {
    "isFlipped": false,
    "isReversed": false,
    "flipCount": 0,
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  1: {
    "isFlipped": false,
    "isReversed": false,
    "flipCount": 0,
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  2: {
    "isFlipped": false,
    "isReversed": false,
    "flipCount": 0,
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  3: {
    "isFlipped": false,
    "isReversed": false,
    "flipCount": 0,
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  4: {
    "isFlipped": false,
    "isReversed": false,
    "flipCount": 0,
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  5: {
    "isFlipped": false,
    "isReversed": false,
    "flipCount": 0,
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  6: {
    "isFlipped": false,
    "isReversed": false,
    "flipCount": 0,
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  7: {
    "isFlipped": false,
    "isReversed": false,
    "flipCount": 0,
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  8: {
    "isFlipped": false,
    "isReversed": false,
    "flipCount": 0,
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  9: {
    "isFlipped": false,
    "isReversed": false,
    "flipCount": 0,
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
  10: {
    "isFlipped": false,
    "isReversed": false,
    "flipCount": 0,
    "cardSubtitle": "",
    "cardImage": "",
    "cardColor": null,
    "cardTitleColor": null,
  },
};